// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: secscan.proto

package secscan

import (
	l8common "github.com/saichler/l8common/go/types/l8common"
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanStatus int32

const (
	ScanStatus_SCAN_STATUS_UNSPECIFIED ScanStatus = 0
	ScanStatus_SCAN_STATUS_PENDING     ScanStatus = 1
	ScanStatus_SCAN_STATUS_SCANNING    ScanStatus = 2
	ScanStatus_SCAN_STATUS_COMPLETED   ScanStatus = 3
	ScanStatus_SCAN_STATUS_FAILED      ScanStatus = 4
	ScanStatus_SCAN_STATUS_MISSING     ScanStatus = 5
	// Trivy failed with a registry auth error (denied/unauthorized) and no
	// usable credential was found for the image's registry host -- distinct
	// from FAILED so the UI can offer a "provide credentials and retry"
	// action instead of just reporting a dead end.
	ScanStatus_SCAN_STATUS_AUTH_REQUIRED ScanStatus = 6
)

// Enum value maps for ScanStatus.
var (
	ScanStatus_name = map[int32]string{
		0: "SCAN_STATUS_UNSPECIFIED",
		1: "SCAN_STATUS_PENDING",
		2: "SCAN_STATUS_SCANNING",
		3: "SCAN_STATUS_COMPLETED",
		4: "SCAN_STATUS_FAILED",
		5: "SCAN_STATUS_MISSING",
		6: "SCAN_STATUS_AUTH_REQUIRED",
	}
	ScanStatus_value = map[string]int32{
		"SCAN_STATUS_UNSPECIFIED":   0,
		"SCAN_STATUS_PENDING":       1,
		"SCAN_STATUS_SCANNING":      2,
		"SCAN_STATUS_COMPLETED":     3,
		"SCAN_STATUS_FAILED":        4,
		"SCAN_STATUS_MISSING":       5,
		"SCAN_STATUS_AUTH_REQUIRED": 6,
	}
)

func (x ScanStatus) Enum() *ScanStatus {
	p := new(ScanStatus)
	*p = x
	return p
}

func (x ScanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_secscan_proto_enumTypes[0].Descriptor()
}

func (ScanStatus) Type() protoreflect.EnumType {
	return &file_secscan_proto_enumTypes[0]
}

func (x ScanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScanStatus.Descriptor instead.
func (ScanStatus) EnumDescriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_LOW         Severity = 1
	Severity_SEVERITY_MEDIUM      Severity = 2
	Severity_SEVERITY_HIGH        Severity = 3
	Severity_SEVERITY_CRITICAL    Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_LOW",
		2: "SEVERITY_MEDIUM",
		3: "SEVERITY_HIGH",
		4: "SEVERITY_CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_LOW":         1,
		"SEVERITY_MEDIUM":      2,
		"SEVERITY_HIGH":        3,
		"SEVERITY_CRITICAL":    4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_secscan_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_secscan_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{1}
}

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_QUEUED      JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_PARTIAL     JobStatus = 5 // some selected images failed to scan
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_QUEUED",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_PARTIAL",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_QUEUED":      1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_PARTIAL":     5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_secscan_proto_enumTypes[2].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_secscan_proto_enumTypes[2]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{2}
}

type VulnerabilityCounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Critical int32 `protobuf:"varint,1,opt,name=critical,proto3" json:"critical,omitempty"`
	High     int32 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	Medium   int32 `protobuf:"varint,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Low      int32 `protobuf:"varint,4,opt,name=low,proto3" json:"low,omitempty"`
}

func (x *VulnerabilityCounts) Reset() {
	*x = VulnerabilityCounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VulnerabilityCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityCounts) ProtoMessage() {}

func (x *VulnerabilityCounts) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityCounts.ProtoReflect.Descriptor instead.
func (*VulnerabilityCounts) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{0}
}

func (x *VulnerabilityCounts) GetCritical() int32 {
	if x != nil {
		return x.Critical
	}
	return 0
}

func (x *VulnerabilityCounts) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *VulnerabilityCounts) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *VulnerabilityCounts) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

type Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string              `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name       string              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsActive   bool                `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	AuditInfo  *l8common.AuditInfo `protobuf:"bytes,4,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *Customer) Reset() {
	*x = Customer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{1}
}

func (x *Customer) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Customer) GetAuditInfo() *l8common.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type CustomerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*Customer       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *CustomerList) Reset() {
	*x = CustomerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerList) ProtoMessage() {}

func (x *CustomerList) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerList.ProtoReflect.Descriptor instead.
func (*CustomerList) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerList) GetList() []*Customer {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CustomerList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ImageCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId string              `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CustomerId string              `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Name       string              `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ColorCode  string              `protobuf:"bytes,4,opt,name=color_code,json=colorCode,proto3" json:"color_code,omitempty"`
	AuditInfo  *l8common.AuditInfo `protobuf:"bytes,5,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *ImageCategory) Reset() {
	*x = ImageCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageCategory) ProtoMessage() {}

func (x *ImageCategory) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageCategory.ProtoReflect.Descriptor instead.
func (*ImageCategory) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{3}
}

func (x *ImageCategory) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ImageCategory) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ImageCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageCategory) GetColorCode() string {
	if x != nil {
		return x.ColorCode
	}
	return ""
}

func (x *ImageCategory) GetAuditInfo() *l8common.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type ImageCategoryList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*ImageCategory  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ImageCategoryList) Reset() {
	*x = ImageCategoryList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageCategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageCategoryList) ProtoMessage() {}

func (x *ImageCategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageCategoryList.ProtoReflect.Descriptor instead.
func (*ImageCategoryList) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{4}
}

func (x *ImageCategoryList) GetList() []*ImageCategory {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ImageCategoryList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ImageGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageGroupId    string               `protobuf:"bytes,1,opt,name=image_group_id,json=imageGroupId,proto3" json:"image_group_id,omitempty"`
	CustomerId      string               `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ImageName       string               `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`                      // grouping key
	CategoryId      string               `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`                   // ref ImageCategory by ID, empty = Uncategorized
	ImageRefCount   int32                `protobuf:"varint,5,opt,name=image_ref_count,json=imageRefCount,proto3" json:"image_ref_count,omitempty"`       // cached
	LatestBuildDate int64                `protobuf:"varint,6,opt,name=latest_build_date,json=latestBuildDate,proto3" json:"latest_build_date,omitempty"` // cached, for default sort
	NewestCounts    *VulnerabilityCounts `protobuf:"bytes,7,opt,name=newest_counts,json=newestCounts,proto3" json:"newest_counts,omitempty"`             // cached: total_counts of the newest scanned ImageRef in this group
	OldestCounts    *VulnerabilityCounts `protobuf:"bytes,8,opt,name=oldest_counts,json=oldestCounts,proto3" json:"oldest_counts,omitempty"`             // cached: total_counts of the oldest scanned ImageRef in this group
	AuditInfo       *l8common.AuditInfo  `protobuf:"bytes,9,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
	// Phase 2 addition (see PROGRESS.md): count of ImageRef rows in this
	// group with scan_status=COMPLETED. The canonical Reduction % "N/A"
	// rule (PRD §10) needs "fewer than 2 scanned image refs" /  "newest and
	// oldest resolve to the same image ref" -- neither is derivable from
	// newest_counts/oldest_counts alone (two different refs can coincide on
	// identical counts), and every consumer of this figure (CSV, dashboard,
	// Group Detail Trend panel) only ever has these cached ImageGroup
	// fields to work with, never the underlying ImageRef rows.
	ScannedRefCount int32 `protobuf:"varint,10,opt,name=scanned_ref_count,json=scannedRefCount,proto3" json:"scanned_ref_count,omitempty"`
}

func (x *ImageGroup) Reset() {
	*x = ImageGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGroup) ProtoMessage() {}

func (x *ImageGroup) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGroup.ProtoReflect.Descriptor instead.
func (*ImageGroup) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{5}
}

func (x *ImageGroup) GetImageGroupId() string {
	if x != nil {
		return x.ImageGroupId
	}
	return ""
}

func (x *ImageGroup) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ImageGroup) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *ImageGroup) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ImageGroup) GetImageRefCount() int32 {
	if x != nil {
		return x.ImageRefCount
	}
	return 0
}

func (x *ImageGroup) GetLatestBuildDate() int64 {
	if x != nil {
		return x.LatestBuildDate
	}
	return 0
}

func (x *ImageGroup) GetNewestCounts() *VulnerabilityCounts {
	if x != nil {
		return x.NewestCounts
	}
	return nil
}

func (x *ImageGroup) GetOldestCounts() *VulnerabilityCounts {
	if x != nil {
		return x.OldestCounts
	}
	return nil
}

func (x *ImageGroup) GetAuditInfo() *l8common.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

func (x *ImageGroup) GetScannedRefCount() int32 {
	if x != nil {
		return x.ScannedRefCount
	}
	return 0
}

type ImageGroupList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*ImageGroup     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ImageGroupList) Reset() {
	*x = ImageGroupList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGroupList) ProtoMessage() {}

func (x *ImageGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGroupList.ProtoReflect.Descriptor instead.
func (*ImageGroupList) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{6}
}

func (x *ImageGroupList) GetList() []*ImageGroup {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ImageGroupList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ImageRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageRefId     string               `protobuf:"bytes,1,opt,name=image_ref_id,json=imageRefId,proto3" json:"image_ref_id,omitempty"`
	CustomerId     string               `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ImageGroupId   string               `protobuf:"bytes,3,opt,name=image_group_id,json=imageGroupId,proto3" json:"image_group_id,omitempty"` // ref ImageGroup by ID
	RepoName       string               `protobuf:"bytes,4,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	Tag            string               `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Digest         string               `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	BuildDate      int64                `protobuf:"varint,7,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	ScanStatus     ScanStatus           `protobuf:"varint,8,opt,name=scan_status,json=scanStatus,proto3,enum=secscan.ScanStatus" json:"scan_status,omitempty"`
	LastScannedAt  int64                `protobuf:"varint,9,opt,name=last_scanned_at,json=lastScannedAt,proto3" json:"last_scanned_at,omitempty"`
	TotalCounts    *VulnerabilityCounts `protobuf:"bytes,10,opt,name=total_counts,json=totalCounts,proto3" json:"total_counts,omitempty"`          // sum-up
	DistinctCounts *VulnerabilityCounts `protobuf:"bytes,11,opt,name=distinct_counts,json=distinctCounts,proto3" json:"distinct_counts,omitempty"` // distinct CVEs
	ScanError      string               `protobuf:"bytes,12,opt,name=scan_error,json=scanError,proto3" json:"scan_error,omitempty"`
	AuditInfo      *l8common.AuditInfo  `protobuf:"bytes,13,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *ImageRef) Reset() {
	*x = ImageRef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRef) ProtoMessage() {}

func (x *ImageRef) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRef.ProtoReflect.Descriptor instead.
func (*ImageRef) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{7}
}

func (x *ImageRef) GetImageRefId() string {
	if x != nil {
		return x.ImageRefId
	}
	return ""
}

func (x *ImageRef) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ImageRef) GetImageGroupId() string {
	if x != nil {
		return x.ImageGroupId
	}
	return ""
}

func (x *ImageRef) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *ImageRef) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ImageRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ImageRef) GetBuildDate() int64 {
	if x != nil {
		return x.BuildDate
	}
	return 0
}

func (x *ImageRef) GetScanStatus() ScanStatus {
	if x != nil {
		return x.ScanStatus
	}
	return ScanStatus_SCAN_STATUS_UNSPECIFIED
}

func (x *ImageRef) GetLastScannedAt() int64 {
	if x != nil {
		return x.LastScannedAt
	}
	return 0
}

func (x *ImageRef) GetTotalCounts() *VulnerabilityCounts {
	if x != nil {
		return x.TotalCounts
	}
	return nil
}

func (x *ImageRef) GetDistinctCounts() *VulnerabilityCounts {
	if x != nil {
		return x.DistinctCounts
	}
	return nil
}

func (x *ImageRef) GetScanError() string {
	if x != nil {
		return x.ScanError
	}
	return ""
}

func (x *ImageRef) GetAuditInfo() *l8common.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type ImageRefList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*ImageRef       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ImageRefList) Reset() {
	*x = ImageRefList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRefList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRefList) ProtoMessage() {}

func (x *ImageRefList) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRefList.ProtoReflect.Descriptor instead.
func (*ImageRefList) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{8}
}

func (x *ImageRefList) GetList() []*ImageRef {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ImageRefList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Cve is a global catalog entity -- not customer-scoped, no deny rule.
// Normalizes each CVE's canonical data once instead of repeating it on
// every finding; also the Prime Object a future cross-image "which
// images have CVE-X" query would target.
type Cve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CveId     string              `protobuf:"bytes,1,opt,name=cve_id,json=cveId,proto3" json:"cve_id,omitempty"` // natural key, e.g. "CVE-2023-1234" -- no generated ID needed
	Severity  Severity            `protobuf:"varint,2,opt,name=severity,proto3,enum=secscan.Severity" json:"severity,omitempty"`
	Title     string              `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AuditInfo *l8common.AuditInfo `protobuf:"bytes,4,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *Cve) Reset() {
	*x = Cve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cve) ProtoMessage() {}

func (x *Cve) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cve.ProtoReflect.Descriptor instead.
func (*Cve) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{9}
}

func (x *Cve) GetCveId() string {
	if x != nil {
		return x.CveId
	}
	return ""
}

func (x *Cve) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Cve) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Cve) GetAuditInfo() *l8common.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type CveList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*Cve            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *CveList) Reset() {
	*x = CveList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CveList) ProtoMessage() {}

func (x *CveList) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CveList.ProtoReflect.Descriptor instead.
func (*CveList) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{10}
}

func (x *CveList) GetList() []*Cve {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CveList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ImageRefCve is one Trivy finding: "package P in ImageRef R was found
// vulnerable to Cve C." A Prime Object (see PRD §8) -- despite its two
// parent FKs -- specifically so a single image's finding list is a
// normal, server-side-filtered/sorted/paginated root-type query, never
// an embedded repeated field.
type ImageRefCve struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageRefCveId    string              `protobuf:"bytes,1,opt,name=image_ref_cve_id,json=imageRefCveId,proto3" json:"image_ref_cve_id,omitempty"`
	CustomerId       string              `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`   // denormalized from the parent ImageRef, for row scoping
	ImageRefId       string              `protobuf:"bytes,3,opt,name=image_ref_id,json=imageRefId,proto3" json:"image_ref_id,omitempty"` // ref ImageRef by ID
	CveId            string              `protobuf:"bytes,4,opt,name=cve_id,json=cveId,proto3" json:"cve_id,omitempty"`                  // ref Cve by ID
	Severity         Severity            `protobuf:"varint,5,opt,name=severity,proto3,enum=secscan.Severity" json:"severity,omitempty"`  // denormalized from Cve at write time -- this ORM has no join, so sort/filter needs it local
	PackageName      string              `protobuf:"bytes,6,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	InstalledVersion string              `protobuf:"bytes,7,opt,name=installed_version,json=installedVersion,proto3" json:"installed_version,omitempty"`
	FixedVersion     string              `protobuf:"bytes,8,opt,name=fixed_version,json=fixedVersion,proto3" json:"fixed_version,omitempty"`
	Title            string              `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"` // denormalized from Cve -- the finding list needs no lookup to render
	AuditInfo        *l8common.AuditInfo `protobuf:"bytes,10,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *ImageRefCve) Reset() {
	*x = ImageRefCve{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRefCve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRefCve) ProtoMessage() {}

func (x *ImageRefCve) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRefCve.ProtoReflect.Descriptor instead.
func (*ImageRefCve) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{11}
}

func (x *ImageRefCve) GetImageRefCveId() string {
	if x != nil {
		return x.ImageRefCveId
	}
	return ""
}

func (x *ImageRefCve) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ImageRefCve) GetImageRefId() string {
	if x != nil {
		return x.ImageRefId
	}
	return ""
}

func (x *ImageRefCve) GetCveId() string {
	if x != nil {
		return x.CveId
	}
	return ""
}

func (x *ImageRefCve) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *ImageRefCve) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ImageRefCve) GetInstalledVersion() string {
	if x != nil {
		return x.InstalledVersion
	}
	return ""
}

func (x *ImageRefCve) GetFixedVersion() string {
	if x != nil {
		return x.FixedVersion
	}
	return ""
}

func (x *ImageRefCve) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImageRefCve) GetAuditInfo() *l8common.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type ImageRefCveList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*ImageRefCve    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ImageRefCveList) Reset() {
	*x = ImageRefCveList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRefCveList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRefCveList) ProtoMessage() {}

func (x *ImageRefCveList) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRefCveList.ProtoReflect.Descriptor instead.
func (*ImageRefCveList) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{12}
}

func (x *ImageRefCveList) GetList() []*ImageRefCve {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ImageRefCveList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ScanJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanJobId       string              `protobuf:"bytes,1,opt,name=scan_job_id,json=scanJobId,proto3" json:"scan_job_id,omitempty"`
	CustomerId      string              `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ImageRefIds     []string            `protobuf:"bytes,3,rep,name=image_ref_ids,json=imageRefIds,proto3" json:"image_ref_ids,omitempty"`
	Status          JobStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=secscan.JobStatus" json:"status,omitempty"`
	TotalImages     int32               `protobuf:"varint,5,opt,name=total_images,json=totalImages,proto3" json:"total_images,omitempty"`
	CompletedImages int32               `protobuf:"varint,6,opt,name=completed_images,json=completedImages,proto3" json:"completed_images,omitempty"`
	FailedImages    int32               `protobuf:"varint,7,opt,name=failed_images,json=failedImages,proto3" json:"failed_images,omitempty"`
	RequestedAt     int64               `protobuf:"varint,8,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	CompletedAt     int64               `protobuf:"varint,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	RequestedBy     string              `protobuf:"bytes,10,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	AuditInfo       *l8common.AuditInfo `protobuf:"bytes,11,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *ScanJob) Reset() {
	*x = ScanJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanJob) ProtoMessage() {}

func (x *ScanJob) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanJob.ProtoReflect.Descriptor instead.
func (*ScanJob) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{13}
}

func (x *ScanJob) GetScanJobId() string {
	if x != nil {
		return x.ScanJobId
	}
	return ""
}

func (x *ScanJob) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ScanJob) GetImageRefIds() []string {
	if x != nil {
		return x.ImageRefIds
	}
	return nil
}

func (x *ScanJob) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ScanJob) GetTotalImages() int32 {
	if x != nil {
		return x.TotalImages
	}
	return 0
}

func (x *ScanJob) GetCompletedImages() int32 {
	if x != nil {
		return x.CompletedImages
	}
	return 0
}

func (x *ScanJob) GetFailedImages() int32 {
	if x != nil {
		return x.FailedImages
	}
	return 0
}

func (x *ScanJob) GetRequestedAt() int64 {
	if x != nil {
		return x.RequestedAt
	}
	return 0
}

func (x *ScanJob) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *ScanJob) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

func (x *ScanJob) GetAuditInfo() *l8common.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type ScanJobList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*ScanJob        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *ScanJobList) Reset() {
	*x = ScanJobList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanJobList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanJobList) ProtoMessage() {}

func (x *ScanJobList) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanJobList.ProtoReflect.Descriptor instead.
func (*ScanJobList) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{14}
}

func (x *ScanJobList) GetList() []*ScanJob {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ScanJobList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ImgRefAdd: bulk free-text image-reference ingestion (§6.1).
type ImgRefAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId      string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ImageRefStrings []string `protobuf:"bytes,2,rep,name=image_ref_strings,json=imageRefStrings,proto3" json:"image_ref_strings,omitempty"`
}

func (x *ImgRefAddRequest) Reset() {
	*x = ImgRefAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgRefAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgRefAddRequest) ProtoMessage() {}

func (x *ImgRefAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgRefAddRequest.ProtoReflect.Descriptor instead.
func (*ImgRefAddRequest) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{15}
}

func (x *ImgRefAddRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ImgRefAddRequest) GetImageRefStrings() []string {
	if x != nil {
		return x.ImageRefStrings
	}
	return nil
}

type ImgRefAddItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ref    string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ImgRefAddItem) Reset() {
	*x = ImgRefAddItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgRefAddItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgRefAddItem) ProtoMessage() {}

func (x *ImgRefAddItem) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgRefAddItem.ProtoReflect.Descriptor instead.
func (*ImgRefAddItem) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{16}
}

func (x *ImgRefAddItem) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ImgRefAddItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ImgRefAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created []string         `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	Skipped []*ImgRefAddItem `protobuf:"bytes,2,rep,name=skipped,proto3" json:"skipped,omitempty"`
	Errors  []*ImgRefAddItem `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ImgRefAddResponse) Reset() {
	*x = ImgRefAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgRefAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgRefAddResponse) ProtoMessage() {}

func (x *ImgRefAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgRefAddResponse.ProtoReflect.Descriptor instead.
func (*ImgRefAddResponse) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{17}
}

func (x *ImgRefAddResponse) GetCreated() []string {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *ImgRefAddResponse) GetSkipped() []*ImgRefAddItem {
	if x != nil {
		return x.Skipped
	}
	return nil
}

func (x *ImgRefAddResponse) GetErrors() []*ImgRefAddItem {
	if x != nil {
		return x.Errors
	}
	return nil
}

// VulnRep: cross-group CSV vulnerability report (§10). customer_id is
// required -- see PRD §10 for why automatic row-scoping cannot reach a
// custom action-service handler. Response reuses l8api.L8CsvExportResponse.
type VulnRepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *VulnRepRequest) Reset() {
	*x = VulnRepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VulnRepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnRepRequest) ProtoMessage() {}

func (x *VulnRepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnRepRequest.ProtoReflect.Descriptor instead.
func (*VulnRepRequest) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{18}
}

func (x *VulnRepRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// ImgRefDelete: delete one ImageRef and recompute its parent ImageGroup's
// rollup cache in the same call -- a plain ORM DELETE on ImageRef can't do
// this itself, since ImageRefServiceCallback.After() (RecomputeImageGroupCache)
// only fires on PUT/PATCH, never DELETE (l8common.genericCallback, verified
// against its source). Group Detail's per-row Delete button uses this
// instead of DELETE-ing ImageRef directly.
type ImgRefDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageRefId string `protobuf:"bytes,1,opt,name=image_ref_id,json=imageRefId,proto3" json:"image_ref_id,omitempty"`
}

func (x *ImgRefDeleteRequest) Reset() {
	*x = ImgRefDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgRefDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgRefDeleteRequest) ProtoMessage() {}

func (x *ImgRefDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgRefDeleteRequest.ProtoReflect.Descriptor instead.
func (*ImgRefDeleteRequest) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{19}
}

func (x *ImgRefDeleteRequest) GetImageRefId() string {
	if x != nil {
		return x.ImageRefId
	}
	return ""
}

type ImgRefDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageGroupId string `protobuf:"bytes,1,opt,name=image_group_id,json=imageGroupId,proto3" json:"image_group_id,omitempty"`
}

func (x *ImgRefDeleteResponse) Reset() {
	*x = ImgRefDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_secscan_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImgRefDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImgRefDeleteResponse) ProtoMessage() {}

func (x *ImgRefDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secscan_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImgRefDeleteResponse.ProtoReflect.Descriptor instead.
func (*ImgRefDeleteResponse) Descriptor() ([]byte, []int) {
	return file_secscan_proto_rawDescGZIP(), []int{20}
}

func (x *ImgRefDeleteResponse) GetImageGroupId() string {
	if x != nil {
		return x.ImageGroupId
	}
	return ""
}

var File_secscan_proto protoreflect.FileDescriptor

var file_secscan_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6c, 0x38, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x13, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72,
	0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x72,
	0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x64, 0x69, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x65, 0x64, 0x69,
	0x75, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6c, 0x6f, 0x77, 0x22, 0x90, 0x01, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x64, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb8, 0x01,
	0x0a, 0x0d, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61,
	0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x6e, 0x0a, 0x11, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x65,
	0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38,
	0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xcd, 0x03, 0x0a, 0x0a, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x5f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x41, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x63, 0x73,
	0x63, 0x61, 0x6e, 0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x65, 0x73, 0x74, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x0d, 0x6f, 0x6c, 0x64, 0x65, 0x73, 0x74, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73,
	0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x0c, 0x6f, 0x6c, 0x64, 0x65,
	0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69,
	0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c,
	0x38, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x11,
	0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64,
	0x52, 0x65, 0x66, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x68, 0x0a, 0x0e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63,
	0x61, 0x6e, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38,
	0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x92, 0x04, 0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x12,
	0x20, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x70,
	0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x34,
	0x0a, 0x0b, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x53, 0x63,
	0x61, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x73, 0x63, 0x61, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3f, 0x0a, 0x0c,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x56, 0x75, 0x6c,
	0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x45, 0x0a,
	0x0f, 0x64, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x63, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e,
	0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x63, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x63, 0x61, 0x6e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x64, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x95, 0x01,
	0x0a, 0x03, 0x43, 0x76, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x76, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x08,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74,
	0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x5a, 0x0a, 0x07, 0x43, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x43, 0x76, 0x65, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xfe, 0x02, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x43, 0x76,
	0x65, 0x12, 0x27, 0x0a, 0x10, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x63,
	0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x66, 0x43, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x63, 0x76, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x76, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e,
	0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x65, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x32,
	0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x6a, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x43, 0x76,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x43, 0x76, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xaa,
	0x03, 0x0a, 0x07, 0x53, 0x63, 0x61, 0x6e, 0x4a, 0x6f, 0x62, 0x12, 0x1e, 0x0a, 0x0b, 0x73, 0x63,
	0x61, 0x6e, 0x5f, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x63, 0x61, 0x6e, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x49, 0x64, 0x73, 0x12,
	0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x29,
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x38,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x62, 0x0a, 0x0b, 0x53,
	0x63, 0x61, 0x6e, 0x4a, 0x6f, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x65, 0x63, 0x73, 0x63,
	0x61, 0x6e, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x4a, 0x6f, 0x62, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d, 0x65, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x5f, 0x0a, 0x10, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x66, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65,
	0x66, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x22, 0x39, 0x0a, 0x0d, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x66, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x72, 0x65, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x8f, 0x01, 0x0a, 0x11,
	0x49, 0x6d, 0x67, 0x52, 0x65, 0x66, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x30, 0x0a, 0x07, 0x73,
	0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73,
	0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x66, 0x41, 0x64, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x12, 0x2e, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x66, 0x41, 0x64,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x31, 0x0a,
	0x0e, 0x56, 0x75, 0x6c, 0x6e, 0x52, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x37, 0x0a, 0x13, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x66, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x14, 0x49, 0x6d, 0x67,
	0x52, 0x65, 0x66, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x2a, 0xc7, 0x01, 0x0a, 0x0a, 0x53, 0x63, 0x61, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14,
	0x53, 0x43, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x43, 0x41, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x43, 0x41,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47,
	0x10, 0x05, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x43, 0x41, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10,
	0x06, 0x2a, 0x75, 0x0a, 0x08, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a,
	0x14, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x56, 0x45, 0x52,
	0x49, 0x54, 0x59, 0x5f, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x56,
	0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d, 0x10, 0x02, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x48, 0x49, 0x47, 0x48, 0x10,
	0x03, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x45, 0x56, 0x45, 0x52, 0x49, 0x54, 0x59, 0x5f, 0x43, 0x52,
	0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x04, 0x2a, 0x9f, 0x01, 0x0a, 0x09, 0x4a, 0x6f, 0x62,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x16, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x4a, 0x4f, 0x42,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x18, 0x0a, 0x14, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x4a,
	0x4f, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44,
	0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x4a, 0x4f, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x05, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x73, 0x63, 0x61, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_secscan_proto_rawDescOnce sync.Once
	file_secscan_proto_rawDescData = file_secscan_proto_rawDesc
)

func file_secscan_proto_rawDescGZIP() []byte {
	file_secscan_proto_rawDescOnce.Do(func() {
		file_secscan_proto_rawDescData = protoimpl.X.CompressGZIP(file_secscan_proto_rawDescData)
	})
	return file_secscan_proto_rawDescData
}

var file_secscan_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_secscan_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_secscan_proto_goTypes = []interface{}{
	(ScanStatus)(0),              // 0: secscan.ScanStatus
	(Severity)(0),                // 1: secscan.Severity
	(JobStatus)(0),               // 2: secscan.JobStatus
	(*VulnerabilityCounts)(nil),  // 3: secscan.VulnerabilityCounts
	(*Customer)(nil),             // 4: secscan.Customer
	(*CustomerList)(nil),         // 5: secscan.CustomerList
	(*ImageCategory)(nil),        // 6: secscan.ImageCategory
	(*ImageCategoryList)(nil),    // 7: secscan.ImageCategoryList
	(*ImageGroup)(nil),           // 8: secscan.ImageGroup
	(*ImageGroupList)(nil),       // 9: secscan.ImageGroupList
	(*ImageRef)(nil),             // 10: secscan.ImageRef
	(*ImageRefList)(nil),         // 11: secscan.ImageRefList
	(*Cve)(nil),                  // 12: secscan.Cve
	(*CveList)(nil),              // 13: secscan.CveList
	(*ImageRefCve)(nil),          // 14: secscan.ImageRefCve
	(*ImageRefCveList)(nil),      // 15: secscan.ImageRefCveList
	(*ScanJob)(nil),              // 16: secscan.ScanJob
	(*ScanJobList)(nil),          // 17: secscan.ScanJobList
	(*ImgRefAddRequest)(nil),     // 18: secscan.ImgRefAddRequest
	(*ImgRefAddItem)(nil),        // 19: secscan.ImgRefAddItem
	(*ImgRefAddResponse)(nil),    // 20: secscan.ImgRefAddResponse
	(*VulnRepRequest)(nil),       // 21: secscan.VulnRepRequest
	(*ImgRefDeleteRequest)(nil),  // 22: secscan.ImgRefDeleteRequest
	(*ImgRefDeleteResponse)(nil), // 23: secscan.ImgRefDeleteResponse
	(*l8common.AuditInfo)(nil),   // 24: l8common.AuditInfo
	(*l8api.L8MetaData)(nil),     // 25: l8api.L8MetaData
}
var file_secscan_proto_depIdxs = []int32{
	24, // 0: secscan.Customer.audit_info:type_name -> l8common.AuditInfo
	4,  // 1: secscan.CustomerList.list:type_name -> secscan.Customer
	25, // 2: secscan.CustomerList.metadata:type_name -> l8api.L8MetaData
	24, // 3: secscan.ImageCategory.audit_info:type_name -> l8common.AuditInfo
	6,  // 4: secscan.ImageCategoryList.list:type_name -> secscan.ImageCategory
	25, // 5: secscan.ImageCategoryList.metadata:type_name -> l8api.L8MetaData
	3,  // 6: secscan.ImageGroup.newest_counts:type_name -> secscan.VulnerabilityCounts
	3,  // 7: secscan.ImageGroup.oldest_counts:type_name -> secscan.VulnerabilityCounts
	24, // 8: secscan.ImageGroup.audit_info:type_name -> l8common.AuditInfo
	8,  // 9: secscan.ImageGroupList.list:type_name -> secscan.ImageGroup
	25, // 10: secscan.ImageGroupList.metadata:type_name -> l8api.L8MetaData
	0,  // 11: secscan.ImageRef.scan_status:type_name -> secscan.ScanStatus
	3,  // 12: secscan.ImageRef.total_counts:type_name -> secscan.VulnerabilityCounts
	3,  // 13: secscan.ImageRef.distinct_counts:type_name -> secscan.VulnerabilityCounts
	24, // 14: secscan.ImageRef.audit_info:type_name -> l8common.AuditInfo
	10, // 15: secscan.ImageRefList.list:type_name -> secscan.ImageRef
	25, // 16: secscan.ImageRefList.metadata:type_name -> l8api.L8MetaData
	1,  // 17: secscan.Cve.severity:type_name -> secscan.Severity
	24, // 18: secscan.Cve.audit_info:type_name -> l8common.AuditInfo
	12, // 19: secscan.CveList.list:type_name -> secscan.Cve
	25, // 20: secscan.CveList.metadata:type_name -> l8api.L8MetaData
	1,  // 21: secscan.ImageRefCve.severity:type_name -> secscan.Severity
	24, // 22: secscan.ImageRefCve.audit_info:type_name -> l8common.AuditInfo
	14, // 23: secscan.ImageRefCveList.list:type_name -> secscan.ImageRefCve
	25, // 24: secscan.ImageRefCveList.metadata:type_name -> l8api.L8MetaData
	2,  // 25: secscan.ScanJob.status:type_name -> secscan.JobStatus
	24, // 26: secscan.ScanJob.audit_info:type_name -> l8common.AuditInfo
	16, // 27: secscan.ScanJobList.list:type_name -> secscan.ScanJob
	25, // 28: secscan.ScanJobList.metadata:type_name -> l8api.L8MetaData
	19, // 29: secscan.ImgRefAddResponse.skipped:type_name -> secscan.ImgRefAddItem
	19, // 30: secscan.ImgRefAddResponse.errors:type_name -> secscan.ImgRefAddItem
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_secscan_proto_init() }
func file_secscan_proto_init() {
	if File_secscan_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_secscan_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VulnerabilityCounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Customer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageCategoryList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageGroupList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRefList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CveList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRefCve); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRefCveList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanJobList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgRefAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgRefAddItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgRefAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VulnRepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgRefDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_secscan_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImgRefDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_secscan_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_secscan_proto_goTypes,
		DependencyIndexes: file_secscan_proto_depIdxs,
		EnumInfos:         file_secscan_proto_enumTypes,
		MessageInfos:      file_secscan_proto_msgTypes,
	}.Build()
	File_secscan_proto = out.File
	file_secscan_proto_rawDesc = nil
	file_secscan_proto_goTypes = nil
	file_secscan_proto_depIdxs = nil
}
